version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3102:3102"  # Map host port 3000 to container port 3000
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Exclude node_modules from being overwritten
    environment:
      - NODE_ENV=development
    restart: unless-stopped